[package]
name = "noir_bls12_381_validator"
type = "bin"
authors = []
compiler_version = ">=1.0.0"

[dependencies]
noir_bls_signature = { path = "../noir-bls-signature" }
sha256 = { tag = "v0.3.0", git = "https://github.com/noir-lang/sha256" }
